// app/HA-DrawingAnalyzer/sections/AssumptionsSources.tsx
// Section 10 — Assumptions & sources.

import Section from './Section'

const ASSUMPTIONS = [
  'The AI Drawing Analyzer can reliably identify and relate common drawing objects across revisions.',
  'The AI Drawing Analyzer can process drawings quickly enough to fit within existing user workflows.',
  'Forma has reliable integration with the AI Drawing Analyzer’s structured output.',
  'Target users already work within Autodesk construction and design workflows.',
  'Most analyzed drawings follow standard industry conventions and contain sufficient quality for automated interpretation.',
  'Drawings remain the project source of truth; structured outputs generated by the AI Drawing Analyzer augment existing workflows rather than replace the underlying drawings and documents.',
]

export default function AssumptionsSources() {
  return (
    <Section id="assumptions" eyebrow="Assumptions">
      <div className="max-w-2xl">
        <ul className="flex flex-col gap-1.5">
          {ASSUMPTIONS.map((a, i) => (
            <li key={i} className="font-sans text-[14px] leading-relaxed text-charcoal flex gap-2">
              <span className="text-autodesk-blue mt-1 shrink-0">—</span>
              <span>{a}</span>
            </li>
          ))}
        </ul>
      </div>
    </Section>
  )
}
