// app/HA-DrawingAnalyzer/presentation/deckData.ts
// Real content for the deck. USE_CASES are imported from the live source of
// truth. The remaining blocks are COPIED from module-local consts in the
// section files (which must stay untouched) — keep them in sync by hand.

import { USE_CASE_1, USE_CASE_2, USE_CASE_3, USE_CASE_4 } from '@/app/HA-DrawingAnalyzer/sections/useCaseData'
import type { UseCaseData } from '@/app/HA-DrawingAnalyzer/sections/UseCase'

export const USE_CASES: UseCaseData[] = [USE_CASE_1, USE_CASE_2, USE_CASE_3, USE_CASE_4]

// SOURCE: sections/Prioritization.tsx CRITERIA / ROWS — keep in sync.
export const CRITERIA = ['Impact', 'Platform Leverage', 'Confidence', 'Feasibility'] as const

export type ScoreRow = { useCase: string; scores: number[]; total: number; winner?: boolean }
export const SCORE_ROWS: ScoreRow[] = [
  { useCase: 'Change Validation',          scores: [5, 5, 5, 3], total: 18, winner: true },
  { useCase: 'Context Link',               scores: [5, 5, 4, 3], total: 17 },
  { useCase: 'Coordination Lock',          scores: [5, 4, 3, 2], total: 14 },
  { useCase: 'Program Conformance Review', scores: [4, 5, 2, 2], total: 13 },
]

export type CriterionDef = { title: string; body: string; rubric: [string, string][] }
export const CRITERIA_DEFS: CriterionDef[] = [
  { title: 'Impact', body: 'Magnitude of value delivered if successful.', rubric: [['5', 'Significant user and business impact.'], ['3', 'Meaningful but limited impact.'], ['1', 'Nice-to-have improvement.']] },
  { title: 'Platform Leverage', body: 'Degree to which the use case depends on the unique capabilities of the AI Drawing Analyzer.', rubric: [['5', 'Impossible without drawing intelligence.'], ['3', 'Somewhat benefits from it.'], ['1', 'Mostly unrelated.']] },
  { title: 'Confidence', body: 'Confidence that users will understand, adopt, and realize value from the workflow.', rubric: [['5', 'Clear pain point and obvious value.'], ['3', 'Some adoption or behavior-change risk.'], ['1', 'Significant uncertainty around adoption or value.']] },
  { title: 'Feasibility', body: 'Estimated effort required to deliver a valuable MVP.', rubric: [['5', 'Low effort and limited dependencies.'], ['3', 'Moderate effort or coordination required.'], ['1', 'Significant effort or complexity required.']] },
]

// SOURCE: sections/MVP.tsx SCOPE_IN / SCOPE_OUT — keep in sync.
export const SCOPE_IN = [
  'Compare two versions of a single drawing sheet.',
  'Detect added, removed, and modified objects.',
  'Generate visual previews of detected changes.',
  'Approve detected changes and submit review.',
  'Cancel review submission and return to editing.',
]
export const SCOPE_OUT = [
  'Manual addition of undetected changes.',
  'Approval or rejection of individual detected changes.',
  'Generate human-readable change descriptions.',
  'Automatic filtering of cosmetic or low-impact changes.',
  'Change severity scoring and risk classification.',
  'Historical change reports.',
  'Multi-sheet drawing sets.',
]

// SOURCE: sections/AssumptionsSources.tsx ASSUMPTIONS — keep in sync.
export const ASSUMPTIONS = [
  'The AI Drawing Analyzer can reliably identify and relate common drawing objects across revisions.',
  'The AI Drawing Analyzer can process drawings quickly enough to fit within existing user workflows.',
  'Forma has reliable integration with the AI Drawing Analyzer’s structured output.',
  'Target users already work within Autodesk construction and design workflows.',
  'Most analyzed drawings follow standard industry conventions and contain sufficient quality for automated interpretation.',
  'Drawings remain the project source of truth; structured outputs generated by the AI Drawing Analyzer augment existing workflows rather than replace the underlying drawings and documents.',
  'The AI Drawing Analyzer is assumed to analyze and interpret drawings, not create or modify design content.',
]

// SOURCE: sections/KeyUnknowns.tsx VARIABLES — keep in sync.
export const VARIABLES = [
  { label: 'Accuracy', body: 'What confidence threshold should be required before a detected change is surfaced to the user?' },
  { label: 'Latency',  body: 'What response time is required for Change Validation to fit naturally into the review submission workflow?' },
  { label: 'Cost',     body: 'Can change validation run on every review initiated while remaining economically viable at project scale?' },
]

// Construction lifecycle for slide 3 — phases (initials + name) and the
// higher-level stage groups that bracket them (modeled on the AEC reference).
export type LifecyclePhase = { initials: string; name: string; muted?: boolean }
export const LIFECYCLE_PHASES: LifecyclePhase[] = [
  { initials: 'PD', name: 'Pre Design' },
  { initials: 'SD', name: 'Schematic Design' },
  { initials: 'DD', name: 'Design Development' },
  { initials: 'BP', name: 'Building Permit', muted: true },
  { initials: 'CD', name: 'Construction Documents' },
  { initials: 'BN', name: 'Bidding & Negotiation', muted: true },
  { initials: 'CA', name: 'Construction Administration' },
]

export type LifecycleGroup = { label: string; start: number; span: number; muted?: boolean }
export const LIFECYCLE_GROUPS: LifecycleGroup[] = [
  { label: 'Research', start: 0, span: 1 },
  { label: 'Design + Coordination + Planning', start: 1, span: 4 },
  { label: 'Pricing', start: 5, span: 1, muted: true },
  { label: 'Construction', start: 6, span: 1 },
]

export const APPROACH_FLOW = ['Lifecycle', 'Bottlenecks', 'Use Cases', 'Prioritization', 'MVP']

// Recommendation pillars (titles from brief; supporting lines adjustable).
export const RECOMMENDATION_PILLARS = [
  { title: 'Highest Confidence', body: 'Clear pain point, obvious value, minimal behavior change.' },
  { title: 'Highest Platform Leverage', body: 'Depends directly on object-level change detection.' },
  { title: 'Fastest Learning', body: 'Lowest-effort MVP that validates the core hypothesis quickly.' },
]

// Demo assets (already committed under /public).
export const DEMO_POSTER = '/drawinganalyzer/ha-drawing-analyzer-poster.jpg'
export const DEMO_HREF = '/HA-DrawingAnalyzer/demo'
